// 頻出英語定型句データ（例として5件。後で100件に拡張可能）
import type { Phrase } from "./PhraseCard";

export const phrases: Phrase[] = [
  { id: "phrase1", phrase: "I'd like to...", example: "I'd like to order a coffee.", translation: "コーヒーを注文したいです。" },
  { id: "phrase2", phrase: "Could you...?", example: "Could you help me with this?", translation: "これを手伝っていただけますか？" },
  { id: "phrase3", phrase: "How about...?", example: "How about going for a walk?", translation: "散歩に行くのはどうですか？" },
  { id: "phrase4", phrase: "I'm looking forward to...", example: "I'm looking forward to seeing you.", translation: "お会いできるのを楽しみにしています。" },
  { id: "phrase5", phrase: "It depends on...", example: "It depends on the weather.", translation: "天気次第です。" },
  { id: "phrase6", phrase: "I'm not sure.", example: "I'm not sure about that.", translation: "それについてはよく分かりません。" },
  { id: "phrase7", phrase: "Let me know.", example: "Let me know if you need anything.", translation: "何かあれば教えてください。" },
  { id: "phrase8", phrase: "I'll be right back.", example: "Wait here. I'll be right back.", translation: "ここで待っててください。すぐ戻ります。" },
  { id: "phrase9", phrase: "That sounds good.", example: "Dinner at 7? That sounds good.", translation: "7時に夕食？いいですね。" },
  { id: "phrase10", phrase: "I'm afraid that...", example: "I'm afraid that I can't come.", translation: "残念ですが行けません。" },
  { id: "phrase11", phrase: "What do you mean?", example: "What do you mean by that?", translation: "それはどういう意味ですか？" },
  { id: "phrase12", phrase: "It's up to you.", example: "Where do you want to eat? It's up to you.", translation: "どこで食べる？君に任せるよ。" },
  { id: "phrase13", phrase: "Take your time.", example: "No rush. Take your time.", translation: "急がなくていいですよ。" },
  { id: "phrase14", phrase: "I'm just looking.", example: "Can I help you? — I'm just looking.", translation: "見ているだけです。" },
  { id: "phrase15", phrase: "I have no idea.", example: "Why is it broken? I have no idea.", translation: "なぜ壊れたのか全く分かりません。" },
  { id: "phrase16", phrase: "It doesn't matter.", example: "Which color? It doesn't matter.", translation: "どの色でも構いません。" },
  { id: "phrase17", phrase: "I'm used to...", example: "I'm used to waking up early.", translation: "早起きには慣れています。" },
  { id: "phrase18", phrase: "I'm not sure if...", example: "I'm not sure if I can go.", translation: "行けるかどうか分かりません。" },
  { id: "phrase19", phrase: "Thanks anyway.", example: "Sorry, I can't help. — Thanks anyway.", translation: "いずれにせよありがとう。" },
  { id: "phrase20", phrase: "That's a good point.", example: "That's a good point. I hadn't thought of that.", translation: "それは良い指摘ですね。" },
  { id: "phrase21", phrase: "I'm looking for...", example: "I'm looking for a book on history.", translation: "歴史の本を探しています。" },
  { id: "phrase22", phrase: "What do you think?", example: "What do you think about this plan?", translation: "この計画についてどう思いますか？" },
  { id: "phrase23", phrase: "It's not my thing.", example: "I don't like horror movies. It's not my thing.", translation: "ホラー映画は苦手です。" },
  { id: "phrase24", phrase: "It can't be helped.", example: "We missed the train. It can't be helped.", translation: "電車に乗り遅れた。仕方ないね。" },
  { id: "phrase25", phrase: "No problem.", example: "Thank you! — No problem.", translation: "どういたしまして。" },
  { id: "phrase26", phrase: "That's too bad.", example: "You lost your wallet? That's too bad.", translation: "財布をなくしたの？それは残念ですね。" },
  { id: "phrase27", phrase: "I'm on my way.", example: "I'm on my way to the station.", translation: "今駅に向かっています。" },
  { id: "phrase28", phrase: "I'm in a hurry.", example: "Sorry, I'm in a hurry.", translation: "すみません、急いでいます。" },
  { id: "phrase29", phrase: "I see.", example: "Oh, I see.", translation: "なるほど。" },
  { id: "phrase30", phrase: "I hope so.", example: "Will it be sunny tomorrow? I hope so.", translation: "明日は晴れるといいですね。" },
  { id: "phrase31", phrase: "I'm not sure yet.", example: "Are you coming? I'm not sure yet.", translation: "行くかどうかまだ分かりません。" },
  { id: "phrase32", phrase: "I'm sorry to hear that.", example: "My dog died. — I'm sorry to hear that.", translation: "それはお気の毒に。" },
  { id: "phrase33", phrase: "Just in case.", example: "Take an umbrella, just in case.", translation: "念のため傘を持っていって。" },
  { id: "phrase34", phrase: "I'm not feeling well.", example: "I'm not feeling well today.", translation: "今日は体調が良くありません。" },
  { id: "phrase35", phrase: "That's interesting.", example: "He speaks five languages. That's interesting.", translation: "それは面白いですね。" },
  { id: "phrase36", phrase: "It's none of your business.", example: "Why do you care? It's none of your business.", translation: "あなたには関係ありません。" },
  { id: "phrase37", phrase: "I'm sorry, I didn't catch that.", example: "Could you repeat that? I'm sorry, I didn't catch that.", translation: "すみません、聞き取れませんでした。" },
  { id: "phrase38", phrase: "I'm afraid so.", example: "Is it closed? — I'm afraid so.", translation: "残念ですが、そうです。" },
  { id: "phrase39", phrase: "It's up to you.", example: "What should we do? It's up to you.", translation: "どうするかは君次第です。" },
  { id: "phrase40", phrase: "It's on me.", example: "Lunch is on me today.", translation: "今日のランチは私のおごりです。" },
  { id: "phrase41", phrase: "Long time no see.", example: "Hey! Long time no see!", translation: "久しぶり！" },
  { id: "phrase42", phrase: "I'm starving.", example: "Let's eat. I'm starving.", translation: "お腹ペコペコです。" },
  { id: "phrase43", phrase: "I'm full.", example: "No more, thanks. I'm full.", translation: "もうお腹いっぱいです。" },
  { id: "phrase44", phrase: "I'm broke.", example: "I can't go out. I'm broke.", translation: "お金がありません。" },
  { id: "phrase45", phrase: "I'm lost.", example: "Can you help me? I'm lost.", translation: "道に迷いました。" },
  { id: "phrase46", phrase: "Bless you!", example: "(after a sneeze) Bless you!", translation: "（くしゃみの後に）お大事に！" },
  { id: "phrase47", phrase: "That's enough.", example: "Stop it. That's enough.", translation: "もう十分です。" },
  { id: "phrase48", phrase: "I'm home.", example: "I'm home!", translation: "ただいま！" },
  { id: "phrase49", phrase: "Make yourself at home.", example: "Come in and make yourself at home.", translation: "どうぞごゆっくり。" },
  { id: "phrase50", phrase: "Help yourself.", example: "Help yourself to some snacks.", translation: "ご自由にどうぞ。" },
  { id: "phrase51", phrase: "Just kidding.", example: "Relax, I'm just kidding.", translation: "冗談ですよ。" },
  { id: "phrase52", phrase: "I'm impressed.", example: "You finished already? I'm impressed.", translation: "もう終わったの？すごいですね。" },
  { id: "phrase53", phrase: "I'm not in the mood.", example: "Sorry, I'm not in the mood for jokes.", translation: "冗談の気分じゃありません。" },
  { id: "phrase54", phrase: "It makes sense.", example: "Now it makes sense.", translation: "これで納得です。" },
  { id: "phrase55", phrase: "Not really.", example: "Do you like sushi? Not really.", translation: "寿司はあまり好きじゃありません。" },
  { id: "phrase56", phrase: "I'm not sure what you mean.", example: "Could you explain? I'm not sure what you mean.", translation: "どういう意味か分かりません。" },
  { id: "phrase57", phrase: "That depends.", example: "Will you come? That depends.", translation: "行くかどうかは場合によります。" },
  { id: "phrase58", phrase: "I'm not interested.", example: "Thanks, but I'm not interested.", translation: "ありがとう、でも興味ありません。" },
  { id: "phrase59", phrase: "I can't wait.", example: "I can't wait to see you!", translation: "会うのが待ちきれません！" },
  { id: "phrase60", phrase: "I'm sorry for the trouble.", example: "I'm sorry for the trouble.", translation: "ご迷惑をおかけしてすみません。" },
  { id: "phrase61", phrase: "I don't mind.", example: "Do you mind if I open the window? — I don't mind.", translation: "窓を開けてもいいですか？—構いませんよ。" },
  { id: "phrase62", phrase: "I'm not sure what to do.", example: "I'm not sure what to do next.", translation: "次に何をすればいいのか分かりません。" },
  { id: "phrase63", phrase: "It's not fair.", example: "That's not fair!", translation: "それは不公平です！" },
  { id: "phrase64", phrase: "I can't help it.", example: "Sorry, I can't help it.", translation: "ごめんなさい、どうしようもありません。" },
  { id: "phrase65", phrase: "It's not worth it.", example: "It's not worth it to argue.", translation: "口論する価値はありません。" },
  { id: "phrase66", phrase: "I'm not sure if that's right.", example: "I'm not sure if that's right.", translation: "それが正しいか分かりません。" },
  { id: "phrase67", phrase: "I can't believe it.", example: "I can't believe it!", translation: "信じられません！" },
  { id: "phrase68", phrase: "That's amazing!", example: "You got the job? That's amazing!", translation: "就職できたの？すごい！" },
  { id: "phrase69", phrase: "I'm not sure why.", example: "I'm not sure why it happened.", translation: "なぜそうなったのか分かりません。" },
  { id: "phrase70", phrase: "I'm proud of you.", example: "You did great. I'm proud of you.", translation: "よく頑張ったね。誇りに思います。" },
  { id: "phrase71", phrase: "It's not my fault.", example: "It's not my fault.", translation: "私のせいではありません。" },
  { id: "phrase72", phrase: "That reminds me.", example: "That reminds me, I have to call him.", translation: "そういえば、彼に電話しないと。" },
  { id: "phrase73", phrase: "I can't stand it.", example: "I can't stand the noise.", translation: "この騒音には耐えられません。" },
  { id: "phrase74", phrase: "I'm not sure how.", example: "I'm not sure how to use this.", translation: "これの使い方が分かりません。" },
  { id: "phrase75", phrase: "It's not a big deal.", example: "Don't worry. It's not a big deal.", translation: "心配しないで。大したことじゃないです。" },
  { id: "phrase76", phrase: "I'm sorry, I'm late.", example: "I'm sorry, I'm late.", translation: "遅れてごめんなさい。" },
  { id: "phrase77", phrase: "That's funny.", example: "That's funny!", translation: "それは面白いですね！" },
  { id: "phrase78", phrase: "I'm just kidding.", example: "Don't be mad. I'm just kidding.", translation: "怒らないで。冗談ですよ。" },
  { id: "phrase79", phrase: "I'm not in a hurry.", example: "Take your time. I'm not in a hurry.", translation: "急いでいません。" },
  { id: "phrase80", phrase: "It's not my style.", example: "That shirt is not my style.", translation: "そのシャツは私の好みじゃありません。" },
  { id: "phrase81", phrase: "I'm not sure where.", example: "I'm not sure where to go.", translation: "どこに行けばいいか分かりません。" },
  { id: "phrase82", phrase: "It's not allowed.", example: "Smoking is not allowed here.", translation: "ここは禁煙です。" },
  { id: "phrase83", phrase: "It's not enough.", example: "This isn't enough.", translation: "これでは足りません。" },
  { id: "phrase84", phrase: "That's impossible.", example: "That's impossible!", translation: "それは無理です！" },
  { id: "phrase85", phrase: "I can't afford it.", example: "I can't afford a new car.", translation: "新しい車を買う余裕はありません。" },
  { id: "phrase86", phrase: "I'm not sure when.", example: "I'm not sure when I'll arrive.", translation: "いつ着くか分かりません。" },
  { id: "phrase87", phrase: "That's enough for now.", example: "That's enough for now.", translation: "今はこれで十分です。" },
  { id: "phrase88", phrase: "I'm not sure who.", example: "I'm not sure who to ask.", translation: "誰に聞けばいいか分かりません。" },
  { id: "phrase89", phrase: "It's not my responsibility.", example: "That's not my responsibility.", translation: "それは私の責任ではありません。" },
  { id: "phrase90", phrase: "It's not worth worrying about.", example: "It's not worth worrying about.", translation: "心配する価値はありません。" },
  { id: "phrase91", phrase: "I'm not sure what happened.", example: "I'm not sure what happened.", translation: "何が起きたのか分かりません。" },
  { id: "phrase92", phrase: "It's not my decision.", example: "It's not my decision to make.", translation: "それは私が決めることではありません。" },
  { id: "phrase93", phrase: "I'm not sure if it's possible.", example: "I'm not sure if it's possible.", translation: "それが可能かどうか分かりません。" },
  { id: "phrase94", phrase: "It's not my business.", example: "It's not my business.", translation: "私には関係ありません。" },
  { id: "phrase95", phrase: "I'm not sure if I understand.", example: "I'm not sure if I understand.", translation: "理解できているか分かりません。" },
  { id: "phrase96", phrase: "It's not a problem.", example: "It's not a problem at all.", translation: "全く問題ありません。" },
  { id: "phrase97", phrase: "I'm not sure what you want.", example: "I'm not sure what you want.", translation: "あなたが何を望んでいるのか分かりません。" },
  { id: "phrase98", phrase: "It's not like that.", example: "It's not like that.", translation: "そういうことではありません。" },
  { id: "phrase99", phrase: "I'm not sure if I can help.", example: "I'm not sure if I can help.", translation: "お力になれるか分かりません。" },
  { id: "phrase100", phrase: "That's all for now.", example: "That's all for now.", translation: "今はこれだけです。" }
];
